import time

from Code.CRISPR.CrisprPlanner import CrisprPlanner
from Code.CRISPR.Enum.AminoAcid import AminoAcid
from Code.CRISPR.Enum.DNASection import DNASection
from Code.CRISPR.Enum.RestrictionSiteType import RestrictionSiteType
from Code.CRISPR.NamedTuples.CodonData import CodonData
from Code.CRISPR.NamedTuples.PointMutation import PointMutation
from Code.CRISPR.NamedTuples.MutateSection import MutateSection
from Code.CRISPR.NamedTuples.RestrictionEnzyme import RestrictionEnzyme
from Code.CRISPR.NamedTuples.RestrictionMutation import RestrictionMutation
from Code.CRISPR.NamedTuples.RestrictionSite import RestrictionSite
from Code.CRISPR.NamedTuples.SequenceSites import SequenceSites
from Code.Files.FileReader import FileReader


def initiate_cp(complete_fields=True, aa_mutation_site=287, start_crrna_index=1150, to_aa=AminoAcid.GLUTAMINE):
    worm_gene_name = 'cct-1'
    nuc_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=aa_mutation_site, sense_strand=nuc_seq)
    cp.initiate_crispr(check_consistency=True)
    chosen_crrna, crrna_strand = cp.get_crrna(window_size=30, PAM_size=3, start_crrna_index=start_crrna_index)
    if complete_fields:
        cp.complete_fields(crrna_strand, to_aa=to_aa, chosen_crrna=chosen_crrna)
    return cp


test1 = False
if test1:
    repo_1_sense_strand = "ATGGACTTTCAGAACAGAGCTGGAGGAAAAACGGGAAGCGGAGGAGTGGCTTCGGCCGCCGATGCTGGTGTTGATCGACGGGAACGGCTCCGCCAGTTGGCTCTAGAGACAATTGATCTTCAAAAGGATCCGTATTTCATGCGAAATCACATTGGAACGTACGAATGCAAGCTGTGTCTTACTCTTCACAACAATGAAGGATCTTATTTGGCACATACACAAGGAAAGAAGCATCAAGCGAATCTTGCACGGCGTGCCGCTAAAGAACAATCTGAACAACCATTTCTACCAGCTCCACAGAAAGCTGCAGTTGAAACTAAAAAGTTTGTGAAAATCGGACGTCCTGGATACAAGGTAACAAAAGAACGTGATCCAGGAGCTGGCCAGCAAGCACTTCTCTTCCAAATTGATTATCCGGAGATTGCTGACGGTATTGCGCCACGTCATCGATTTATGTCTGCTTATGAGCAAAAGATTCAGCCTCCAGACAAGAGATGGCAATACCTCTTGTTTGCTGCTGAGCCGTATGAAACGATTGGATTCAAAATTCCATCAAGgtgaggctttacaacattttagcacttttctatctcatagttacgattaaaaaaattgtatataccaagtaattttttccagAGAAGTTGACAAATCTGAAAAATTTTGGACGATGTGGAACAAAGACACGAAGCAATTCTTCTTACAAGTCGCATTCAAATTGGAACGACTCGATGATCAGCCGTACTATTGAtactctatgtttttatctttttgatttcaaaattcaaaacaattttttcgtgtttttcgatgatctaacaataaattattttcctttttttt"
    # sense_strand = "gcattgtaaggagaagccgggtaattaatacgataggcgccgttacaaaccgccaactggtgatcattattctctgaaaATGGAGCCGCGGACAGACGGAGCAGAATGCGGTGTCCAGgtattaattttccccgcctagattttccaatttcatattgttttcagGTATTTTGTCGTATTCGGCCGCTCAATAAGACCGAGGAGAAGAATGCGGACCGTTTCCTGCCCAAATTCCCTTCCGAGGACAGTATATCGCTTGGGgtgagtaatacaaaggggtcatagggaacaattatgtcaacagggacgggaagcacgggggatgcaggtgtgtcaattctctcacatgacacattcatctgtttgaaaagtacacgaaaagtgcaaagttgaatatatatatatatatcgattgatttgttggaatttttcagGGAAAAGTATACGTGTTCGATAAAGTGTTCAAGCCGAACACCACGCAAGAGCAAGTGTACAAAGGAGCCGCTTATCACATCGTACAGGATGTATTATCCGGTTATAATGGAACAGTTTTTGCATATGGACAAACATCTTCCGGAAAAACACATACAATGGAGgtaggaattatgaaaaccttgataattacgtagaatgcgacaaagacaatcaagttgtaatatcaacagtgcaaatctttactgattaatgaaaagaaaagtttgagaactaattttcagcagttatttccgaaatcgaatgcccgaaagatttttgataatttttacgtttaaaatattcggcgctcgatgaaattaacaatataatttaattattttcatattttttacagGGAGTAATCGGTGATAATGGCTTGTCGGGAATCATTCCACGTATCGTTGCTGACATCTTTAACCACATTTATAGTATGGACGAGAATCTTCAATTTCACATCAAAGTGTCCTATTATGAAATTTACAACGAGAAGATTCGAGATTTATTAGACCCCGAGAAGGTCAATTTGTCCATTCATGAAGATAAAAATCGAGTGCCATACGTGAAGGGAGCCACCGAACGGTTTGTTGGAGGACCCGATGAGGTTCTTCAGGCAATCGAAGATGGAAAATCCAACAGAATGGTTGCAGTTACGAgtgagtaaacttaaaattaaacaaattaacatgtgaacgaaatttcagACATGAACGAACATTCTTCTCGATCTCATTCCGTCTTCTTGATTACTGTGAAACAAGAACATCAGACAACAAAGAAACAGCTCACCGGAAAGCTTTATCTTGTTGATTTGGCTGGTTCTGAGAAAGTGAGCAAAACTGGAGCTCAAGGAACAGTTTTAGAAGAAGCCAAAAACATCAACAAGTCACTTACTGCACTCGGAATAGTTATTTCAGCATTGGCTGAAGGAACTgtgagttgtttaaattatgaccttcttaaaacgaatatttatttcagAAATCTCATGTTCCATATCGTGATTCCAAACTGACTCGTATTCTTCAAGAATCTCTAGGAGGAAATTCCCGTACTACAGTTATTATTTGTGCTTCTCCGTCACATTTCAACGAAGCTGAAACTAAATCCACACTTTTGTTCGGAGCACGTGCGAAGACTATCAAGAATGTTGTACAAATCAACGAAGAGCTCACAGCAGAAGAATGGAAACGGCGATATGAGAAAGAAAAAGAGAAGAATACTCGATTGGCCGCCCTTCTCCAGGCAGCGGCTTTGGAACTTTCACGCTGGCGTGCTGGAGAATCAGTGTCTGAGGTTGAATGGGTCAATCTATCAGATTCTGCTCAAATGGCTGTGTCGGAAGTTTCTGGTGGGTCGACTCCACTCATGGAACGTTCGATTGCTCCAGCTCCTCCAATGCTAACTTCTACAACTGGCCCGATCACTGACGAAGAGAAGAAGAAGTACGAAGAGGAACGTGTCAAACTGTATCAGCAACTCGACGAGAAAGATGATGAGATTCAAAAAGTTTCGCAAGAGCTTGAGAAGCTTAGACAACAAGTTCTTCTCCAAGAAGAAGCTTTGGGAACTATGCGTGAAAACGAGGAGCTGATCCGTGAAGAGAACAACCGATTCCAAAAAGAAGCTGAAGACAAGCAGCAAGAAGGAAAGGAAATGATGACAGCTCTGGAAGAGATTGCTGTCAACTTGGATGTTCGACAAGCAGAATGCGAAAAATTGAAGAGAGAGTTGGAAGTTGTTCAAGAAGATAACCAGAGTTTGGAAGATCGAATGAACCAAGCAACATCACTCCTCAATGCTCATCTTGACGAATGTGGTCCAAAAATCCGTCATTTCAAAGAAGGAATCTACAATGTTATTCGTGAATTCAACATTGCTGACATTGCCTCTCAAAATGATCAACTTCCTGATCACGATCTTCTGAACCATGTCAGAATCGGAGTTTCAAAACTCTTCTCAGAATACTCTGCTGCGAAAGAGAGCAGTACAGCTGCCGAGCATGATGCTGAAGCGAAACTTGCAGCTGATGTTGCTCGTGTTGAATCTGGTCAAGACGCGGGTAGAATGAAACAATTGCTGGTGAAGGATCAGGCGGCAAAGGAGATCAAGCCACTAACAGATCGTGTCAATATGGAGCTTACAACGTTGAAGAATTTGAAAAAGGAGTTCATGAGAGTACTTGTTGCTCGATGCCAAGCCAATCAAGACACCGAGGGAGAAGATTCTCTCAGTGGACCAGCTCAAAAGCAACGAATTCAGTTCTTGGAGAACAATTTGGACAAGTTGACGAAGGTTCACAAGCAGgtttgtcgtttttattctcattttgattatcttaaaacttgaattttcagCTTGTTCGCGACAATGCCGATTTGCGCGTTGAACTGCCAAAGATGGAAGCTCGTCTTCGTGGTCGTGAAGATCGCATCAAAATATTAGAAACTGCTCTTCGTGATTCGAAGCAACGTAGTCAAGCAGAACGAAAGAAGTATCAACAAGAAGTTGAACGAATCAAGGAAGCTGTTCGACAACGTAACATGCGACGAATGAATGCTCCACAAATTGTGAAGCCAATCCGTCCAGGACAAGTGTATACGTCTCCGTCAGCAGGAATGTCACAAGGAGCTCCAAATGGCTCAAACGgtgtgtttagtcagacatctacaccttcaacatctcgcaatcagataccatcaaaaatgactatttcacagttgattgcagaaatttaagatttttttaaaaattctttagtgctcatgtaatttttcacaagtaattatactatgaattagaattagagtgagtgtttctttttcttcctaccgtattatcaaatttaacagtcttttgtccgtccatttttcactaatcaaagtttttcagCATAAtgtctcccaacaacaacatcaactcatcgtcttctttgatccaatcaatacactgaagactgacattcaaatgcttctctatctctcttcttttcccggctttgtgatatactttcgatgggcttttctgtttattttaaaatctagtaacttatacaattacgcggcttctggaagtttcaacaaaaatatcttcatttggttggttgtgtctccccatttcgttccttggcttctcgtcttccatgtagaatacaaaacttcaaaagctaaaagtatttaaagcttccctccacccccacccaaattgcctttttccgcctttttgttctaatagtctgtttctatacgattttcctgtttcagttttactaatctgacacgaggttttgtctggttcttccccccgtcacccaccaacactcctatgattgttttttgcatgcgtttgagtgtctttaaagcttgcttgctaaatccccctatcattcttcataagaaatcaacttgtttcgtttctgcacaattcggcccccaaatccccgcacatcccaattg"
    repo_1_aa_sequence = "MDFQNRAGGKTGSGGVASAADAGVDRRERLRQLALETIDLQKDPYFMRNHIGTYECKLCLTLHNNEGSYLAHTQGKKHQANLARRAAKEQSEQPFLPAPQKAAVETKKFVKIGRPGYKVTKERDPGAGQQALLFQIDYPEIADGIAPRHRFMSAYEQKIQPPDKRWQYLLFAAEPYETIGFKIPSREVDKSEKFWTMWNKDTKQFFLQVAFKLERLDDQPYY"
    # amino_acid_sequence = "MEPRTDGAECGVQVFCRIRPLNKTEEKNADRFLPKFPSEDSISLGGKVYVFDKVFKPNTTQEQVYKGAAYHIVQDVLSGYNGTVFAYGQTSSGKTHTMEGVIGDNGLSGIIPRIVADIFNHIYSMDENLQFHIKVSYYEIYNEKIRDLLDPEKVNLSIHEDKNRVPYVKGATERFVGGPDEVLQAIEDGKSNRMVAVTNMNEHSSRSHSVFLITVKQEHQTTKKQLTGKLYLVDLAGSEKVSKTGAQGTVLEEAKNINKSLTALGIVISALAEGTKSHVPYRDSKLTRILQESLGGNSRTTVIICASPSHFNEAETKSTLLFGARAKTIKNVVQINEELTAEEWKRRYEKEKEKNTRLAALLQAAALELSRWRAGESVSEVEWVNLSDSAQMAVSEVSGGSTPLMERSIAPAPPMLTSTTGPITDEEKKKYEEERVKLYQQLDEKDDEIQKVSQELEKLRQQVLLQEEALGTMRENEELIREENNRFQKEAEDKQQEGKEMMTALEEIAVNLDVRQAECEKLKRELEVVQEDNQSLEDRMNQATSLLNAHLDECGPKIRHFKEGIYNVIREFNIADIASQNDQLPDHDLLNHVRIGVSKLFSEYSAAKESSTAAEHDAEAKLAADVARVESGQDAGRMKQLLVKDQAAKEIKPLTDRVNMELTTLKNLKKEFMRVLVARCQANQDTEGEDSLSGPAQKQRIQFLENNLDKLTKVHKQLVRDNADLRVELPKMEARLRGREDRIKILETALRDSKQRSQAERKKYQQEVERIKEAVRQRNMRRMNAPQIVKPIRPGQVYTSPSAGMSQGAPNGSNA"
    cp = CrisprPlanner("repo-1",
                       aa_mutation_site=31,
                       sense_strand=repo_1_sense_strand,
                       amino_acid_sequence=repo_1_aa_sequence)
    cp.plan_my_crispr(from_aa=AminoAcid.ARGININE, to_aa=AminoAcid.GLUTAMINE, check_consistency=False)
    # cp.plan_my_crispr(aa_mutation_site=26)

# work2 = False
# if work2:
#     # seq = "GCCCCAACAAT"
#     # demands = {4: 'C', 5: 'A', 6: 'A'}
#     # pam_sites = (6, 8)
#     mutants_dic = {}
#     CrisprPlanner.modify_seq_to_change_restriction_sites("TCCAACA", {2: "C", 3: "A", 4: "A"},
#                                                          mutants=mutants_dic, max_mutations=2, mutations_so_far=0)
#     print(mutants_dic)
#     print(str(len(mutants_dic)))

# irrelevant
test3 = False
if test3:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    mutated_seq = "CCGGACAA"
    CrisprPlanner(worm_gene_name, amino_acid_mutation_site, nt_seq).find_restriction_sites("TCCGCCAG")

test4 = False
if test4:
    a = "AAA"
    b = AminoAcid.ASPARAGINE
    codon_details = CrisprPlanner.how_to_get_b_from_a(a, b)
    print(codon_details)

test5 = False
if test5:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq). \
        plan_my_crispr(from_aa=AminoAcid.ASPARAGINE,
                       to_aa=AminoAcid.SERINE)
test6 = False
if test6:
    print(CrisprPlanner.how_to_get_b_from_a("ACG", AminoAcid.ALANINE))

test7 = False
if test7:
    start = time.time()
    fin = open(r"C:\Users\RZBlab\PycharmProjects\Research-RZB\Code\CRISPR\restriction_enzymes.txt")
    for line in fin:
        lst = line.rstrip("\n").split("\t")
        enzyme_site = lst[0]
        enzyme_name = lst[1]
        parsed_sites_rec = FileReader.find_enzymes_derivatives(enzyme_site, rec=True)
    fin.close()
    end = time.time()
    print(end - start)
    start = time.time()
    fin = open(r"C:\Users\RZBlab\PycharmProjects\Research-RZB\Code\CRISPR\restriction_enzymes.txt")
    for line in fin:
        lst = line.rstrip("\n").split("\t")
        enzyme_site = lst[0]
        enzyme_name = lst[1]
        parsed_sites_iter = FileReader.find_enzymes_derivatives(enzyme_site, rec=False)
    fin.close()
    end = time.time()
    print(end - start)

test8 = False
if test8:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    restriction_sites = CrisprPlanner(gene_name=worm_gene_name,
                                      aa_mutation_site=amino_acid_mutation_site,
                                      sense_strand=nt_seq).restriction_enzymes
test9 = False
if test9:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    crisprPlanner = CrisprPlanner(gene_name=worm_gene_name,
                                  aa_mutation_site=amino_acid_mutation_site,
                                  sense_strand=nt_seq)
    print("finished with the restriction sites list")
    crisprPlanner.find_sites("TTGCA")
    crisprPlanner.find_sites("TCAGA")
    crisprPlanner.find_sites("GATTC")

test10 = False
if test10:
    codon_data1 = CodonData('CGG', SequenceSites(12, 14))
    codon_data2 = CodonData('CGG', SequenceSites(11, 13))
    codon_data3 = CodonData('CGG', SequenceSites(10, 12))
    codon_data4 = CodonData('CGG', SequenceSites(13, 15))
    codon_data5 = CodonData('CGG', SequenceSites(14, 16))

    same_aa_codons = ['CGC', 'CGA', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA']
    section_to_mutate = MutateSection(1, DNASection.PAM_SITE, SequenceSites(12, 14))
    CrisprPlanner.check_outside_codon_mutations(codon_data1, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data1)

    same_aa_codons = ['CGC', 'CGA', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA']
    CrisprPlanner.check_outside_codon_mutations(codon_data2, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data2)

    same_aa_codons = ['CGC', 'CGA', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA']
    CrisprPlanner.check_outside_codon_mutations(codon_data3, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data3)

    same_aa_codons = ['CGC', 'CGA', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA']
    CrisprPlanner.check_outside_codon_mutations(codon_data4, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data4)

    same_aa_codons = ['CGC', 'CGA', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA']
    CrisprPlanner.check_outside_codon_mutations(codon_data5, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data5)

test11 = False
if test11:
    codon_data1 = CodonData('CGG', SequenceSites(24, 26))
    codon_data2 = CodonData('CGG', SequenceSites(25, 27))
    codon_data3 = CodonData('CGG', SequenceSites(26, 28))
    codon_data4 = CodonData('CGG', SequenceSites(8, 10))
    codon_data5 = CodonData('CGG', SequenceSites(9, 11))

    same_aa_codons = ['CGC', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA', 'AGG']
    section_to_mutate = MutateSection(1, DNASection.CR_RNA, SequenceSites(10, 10 + 20 - 1 - 3))
    CrisprPlanner.check_outside_codon_mutations(codon_data1, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data1)

    same_aa_codons = ['CGC', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA', 'AGG']
    CrisprPlanner.check_outside_codon_mutations(codon_data2, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data2)

    same_aa_codons = ['CGC', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA', 'AGG']
    CrisprPlanner.check_outside_codon_mutations(codon_data3, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data3)

    same_aa_codons = ['CGC', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA', 'AGG']
    CrisprPlanner.check_outside_codon_mutations(codon_data4, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data4)

    same_aa_codons = ['CGC', 'CGT', 'AGA', 'AGG', 'ACG', 'CTA', 'AGG']
    CrisprPlanner.check_outside_codon_mutations(codon_data5, same_aa_codons, section_to_mutate)
    print(same_aa_codons, "for", codon_data5)

worm_gene_name = 'cct-1'
amino_acid_mutation_site = 3
nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
mutation_zone = SequenceSites(4, 17)
num_rest_sites = 6

test12 = False
if test12:
    rest_enzyme = RestrictionEnzyme(name='PvuII', site='CAGCTG', derivatives=tuple('CAGCTG'),
                                    full_site='CAG/CTG')
    rest_site = RestrictionSite(SequenceSites(7, 12), rest_enzyme)
    point_mutations = [PointMutation(7, 'T')]
    cp = CrisprPlanner(worm_gene_name, amino_acid_mutation_site, nt_seq)
    seq_to_mutate = cp.mutated_strand[4:17 + 1]
    cp.find_sites(seq_to_mutate)
    print(cp.is_restriction_site_well_removed(point_mutations, rest_site, mutation_zone, num_rest_sites))

test13 = False
if test13:
    rest_enzyme = RestrictionEnzyme(name='MspA1I', site='CMGCKG',
                                    derivatives=tuple('CCGCTG', 'CAGCTG', 'CAGCGG', 'CCGCGG'),
                                    full_site='CMG/CKG')
    rest_site = RestrictionSite(SequenceSites(7, 12), rest_enzyme)
    point_mutations = [PointMutation(8, 'C')]
    cp = CrisprPlanner(worm_gene_name, amino_acid_mutation_site, nt_seq)
    seq_to_mutate = cp.mutated_strand[4:17 + 1]
    cp.find_sites(seq_to_mutate)
    print(cp.is_restriction_site_well_removed(point_mutations, rest_site, mutation_zone, num_rest_sites))

# create parsed restriction enzymes
test14 = False
if test14:
    fin = open(r"C:\Users\Liran\PycharmProjects\Research\Code\CRISPR\restriction_enzymes.txt")
    fout = open(r"C:\Users\Liran\PycharmProjects\Research\Code\CRISPR\parsed_restriction_enzymes.txt", "w")
    for line in fin:
        lst = line.rstrip("\n").split("\t")
        enzyme_site = lst[0]
        filtered_site = FileReader.get_plain_site(enzyme_site)
        enzyme_name = lst[1]
        parsed_sites_rec = FileReader.find_enzymes_derivatives(filtered_site, rec=True)
        fout.write(enzyme_name + "\t" + filtered_site + "\t" + ",".join(parsed_sites_rec) + "\t" + enzyme_site + "\n")
    fin.close()
    fout.close()

# test to check whether the function that takes the parsed enzymes file and turns it to a list works fine
test15 = False
if test15:
    rest_enzyme = RestrictionEnzyme(name='MspA1I', site='CMGCKG', derivatives=('CCGCTG', 'CAGCTG', 'CAGCGG', 'CCGCGG'),
                                    full_site='CMG/CKG')
    rest_site = RestrictionSite(SequenceSites(7, 12), rest_enzyme)
    point_mutations = [PointMutation(8, 'C')]
    cp = CrisprPlanner(worm_gene_name, amino_acid_mutation_site, nt_seq)
    print("Examples out of", len(cp.restriction_enzymes), ":")
    print(cp.restriction_enzymes[0])
    print(cp.restriction_enzymes[1])
    print(cp.restriction_enzymes[2])
    print(cp.restriction_enzymes[11])
    print(cp.restriction_enzymes[12])
    print(cp.restriction_enzymes[34])
    print(cp.restriction_enzymes[50])
    print(cp.restriction_enzymes[60])
    print(cp.restriction_enzymes[80])
    print(cp.restriction_enzymes[100])

work16 = False
# to check sorting by relevant restriction enzymes
if work16:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    enzymes = ['HpyCH4IV', 'DpnII', 'DpnI', 'PacI', 'AscI', 'AvaII', 'DdeI']
    print("Test with enzymes:", enzymes)
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                  favourite_enzymes_names=enzymes).plan_my_crispr(from_aa=AminoAcid.ASPARAGINE,
                                                                  to_aa=AminoAcid.SERINE)

work17 = False
# to check sorting by distance - no other near site
if work17:
    cp = initiate_cp()
    rs = RestrictionSite(index=SequenceSites(start=1162, end=1168),
                         enzyme=RestrictionEnzyme(name='Cac8I', site='GCNNGC',
                                                  derivatives=('GCTGGC', 'GCACGC', 'GCCTGC',
                                                               'GCGAGC', 'GCGTGC', 'GCGCGC',
                                                               'GCTAGC', 'GCTCGC', 'GCTTGC',
                                                               'GCCCGC', 'GCCAGC', 'GCCGGC',
                                                               'GCGGGC', 'GCAGGC', 'GCAAGC',
                                                               'GCATGC'),
                                                  full_site='GCN/NGC'))

    print("distance from other sites within 100 nt distance", cp.check_distance(restriction_site=rs))
    print("rareness:", cp.check_rareness(rs))

work18 = False
# to check sorting by distance - other near site
if work18:
    cp = initiate_cp()
    rs = RestrictionSite(index=SequenceSites(start=1163, end=1167),
                         enzyme=RestrictionEnzyme(name='MspJI', site='CNNR',
                                                  derivatives=('CGGA', 'CTGG', 'CGGG', 'CGAA', 'CATA', 'CAGA', 'CCCA',
                                                               'CACA', 'CCGA', 'CTTG', 'CTAG', 'CGCG', 'CATG', 'CCTG',
                                                               'CTCA', 'CGTG', 'CGAG', 'CACG', 'CGCA', 'CCGG', 'CTCG',
                                                               'CCAG', 'CCAA', 'CTTA', 'CTGA', 'CCCG', 'CGTA', 'CAGG',
                                                               'CAAG', 'CAAA', 'CTAA', 'CCTA'), full_site='CNNR(9/13)'))
    print("distance from other sites within 100 nt distance", cp.check_distance(restriction_site=rs))
    print("rareness:", cp.check_rareness(rs))

mutate_rest_site_test = False
# this test is designed to check what happens if no restriction site is created\removed naturally and we have to insert
# mutations
if mutate_rest_site_test:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    rest_enzyme = RestrictionEnzyme(name='BsaWI', site='WCCGGW', derivatives=('ACCGGA', 'TCCGGA', 'TCCGGT', 'ACCGGT'),
                                    full_site='W/CCGGW')
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq)
    cp.restriction_enzymes = [rest_enzyme]
    cp.plan_my_crispr(from_aa=AminoAcid.ASPARAGINE,
                      to_aa=AminoAcid.SERINE)

# outdated
mutate_rest_site_test1 = False
# this test is designed to check what happens if no restriction site is created\removed naturally and we have to insert
# mutations - more monitored
if mutate_rest_site_test1:
    cp = initiate_cp()
    rest_enzyme = RestrictionEnzyme(name='BsaWI', site='WCCGGW', derivatives=('ACCGGA', 'TCCGGA', 'TCCGGT', 'ACCGGT'),
                                    full_site='W/CCGGW')
    cp.restriction_enzymes = [rest_enzyme]
    mutation_zone = SequenceSites(1162, 1167)
    mutated_sites = [PointMutation(index=1163, new_nucleotide="C"), PointMutation(index=1170, new_nucleotide="A")]
    ssodn_mutation_codon_start = 1162
    mutated_strand = "gtggcaaagcttcttcattgtttgaataatgaaaaacgaatacaaacaactttgaaatcaaaacattaaaacttacaacatttcgttcaataaagtatcatcaaaagaagaaaacaaaagctgaacatgagaatttgggataaggagcagcagatcggaattatgtgagaagcacgcggaaaacagggatatataaacggggtaaacgggaaaatTTAAGCGTGGCAATCATCTCCTCCAAGTGGCTCTTGCTTGTCAAGTTTGATGAGGTCATCAATACGCAATATCGTAATGGCTGCCTCAGTGGCGAACTTCAGAGACTTGACCTTACTAAGAGCTGGCTCCAAAATTCCAGCCTCCTTGTTATCGCGGATCGTGCCTTCTTCGAGATCCAAACCAGCCctaaaaaaagagtgaataaactgactcaaattcagaaaacatgaattagacgctttttctaagcacaaaacgaaattttttgaaataaattattttaattttattacattaagctaacatgtaataacctactctttaaaaaaaacattttcacttacCACTTGAGGTGTTGAAGTTGTGGGATCAATTGAGCTTTGGAGTGGTACGCGCGGAGTTTTGTCACTAAATCAGTAGAATCTCTTGCAGCATTGCTTGCCAAAACCTTCGGAATGATGAGAAGCGCTGAAGCGAATTCAGCAACAGCAAGCTGCTCGCGAGAAGACAAGGTTTGTGCATAAGTTTCAAGGAAAAGACTGAGAGAAGTCTCAACAGCACCTCCTCCAGCCACAAGTTTCTTGCTTTCCAGAACTCTACGAACAACACAGAGTGAGTCGTGAACCGATCTCTCCATTTCATCGAGCATCACATCGTTCGCTCCACGGAGGATAATGCTGCTGGCAGTACGAGATTTCGGTCCCTTGATGAGAATGAGCTCGTCGTCACTAATTCTTTCTTGAACAATTTCATCGGCATGTCCAAGAAGCGAGGCATCGAAAGCTTCATCTCCTTCCAAAGTAGCCAAGGAAACAGTCAATGTGGCTCCAGTAGCTTTGGCAATTCTCTTCAAGTCTGATTTCTTGCATCGACGAACAGCCATAGCTCCAGATTCGACAAATTGCTTCAAGCACAAATCATCGATACCTCCAGTTGTAAGAACAACGCTGGCTCAGGCTTTCAAAATTTTATCAATGCGGCGTTTGGTAATATCGAATTCTctgaaaattccatagcttaaaaagaaacgaatagtttcaactcacTCTCTGCGAATAGCCTCAAGCTTGGCTGGATCTTCAACAACGACTGAAATACCGAGGTGCATCTTAGCCTTCATCAAAGAGAAATCGAGACATGCGATCTTGGCATTTTGAACACGAAGTGGCATGGCCTGACTGGCAACTGTGCAATTGAGTGCATATCCTTTCACCAAAACTGATTCGCGAGCGCTCTTTCCGTGGGCCTTCAGAACATTGACTGCATTGATAGGATAAGTGACTTTCCCGTTATTTTCCACACGAACAGCTTCCGCGGCATCAACAACCAGCTCTCCGAAGAAATCGGCGTCTctgaaaaatcaattttcttgaagcatagacaacaccaaactcacGGTCCGATAATCTTACTGCTCATGGAAGTTTTGGCAGCGTTGACAACTGATTGTCTACCAATCGAGTCGGAAGTGAATGAGATGTTTTCACTAATGTACTTGACGGCTTCCTTGCACGCGAGACGGTAACCATTGATAATAGTCGTCGGATGAACTTTTTGTTTCACAAGCTCATCGGCTCTCTTCAAGAGCTCAGCCGCCACAATAACGACAGAAGTAGTTCCATCTCCGACCTCCTCGTCTTGCAGCTGTGCAAGTTCTACAAGCACTTTTCCAGCCGGATGCTCAACCTCGAGTTGTTTCAGAATTGTGGCTCCGTCATTTGTGACAATGACATCTCCAACATCATCGACAAGCATTTTATCAAGTCCGACAGGGCCAAGAGATGACTTCACAATATTGGCGATCGCAACTGCCGCGGTGActgcaattaattaatgtatacttatattgagctttcggtgttacCATTCTGAGATCTGATGCCTTGTCCAGTAGTTCTTTTACCGGTGAGGGCAAGAATGGAATCTCCAGCTGATGCCATtac"
    cp.get_possible_restriction_sites(mutated_strand, mutation_zone, mutated_sites, ssodn_mutation_codon_start)

mutate_rest_site_test2 = False
# this test is designed to check what happens if no restriction site is created\removed naturally and we have to insert
# mutations - more monitored, using different not recursive function
if mutate_rest_site_test2:
    cp = initiate_cp()
    rest_enzyme = RestrictionEnzyme(name='BsaWI', site='WCCGGW', derivatives=('ACCGGA', 'TCCGGA', 'TCCGGT', 'ACCGGT'),
                                    full_site='W/CCGGW')
    cp.restriction_enzymes = [rest_enzyme]
    mutation_zone = SequenceSites(1162, 1167)
    cp.mutated_sites = [PointMutation(index=1163, new_nucleotide="C"), PointMutation(index=1170, new_nucleotide="A")]
    ssodn_mutation_codon_start = 1162
    cp.mutated_strand = "gtggcaaagcttcttcattgtttgaataatgaaaaacgaatacaaacaactttgaaatcaaaacattaaaacttacaacatttcgttcaataaagtatcatcaaaagaagaaaacaaaagctgaacatgagaatttgggataaggagcagcagatcggaattatgtgagaagcacgcggaaaacagggatatataaacggggtaaacgggaaaatTTAAGCGTGGCAATCATCTCCTCCAAGTGGCTCTTGCTTGTCAAGTTTGATGAGGTCATCAATACGCAATATCGTAATGGCTGCCTCAGTGGCGAACTTCAGAGACTTGACCTTACTAAGAGCTGGCTCCAAAATTCCAGCCTCCTTGTTATCGCGGATCGTGCCTTCTTCGAGATCCAAACCAGCCctaaaaaaagagtgaataaactgactcaaattcagaaaacatgaattagacgctttttctaagcacaaaacgaaattttttgaaataaattattttaattttattacattaagctaacatgtaataacctactctttaaaaaaaacattttcacttacCACTTGAGGTGTTGAAGTTGTGGGATCAATTGAGCTTTGGAGTGGTACGCGCGGAGTTTTGTCACTAAATCAGTAGAATCTCTTGCAGCATTGCTTGCCAAAACCTTCGGAATGATGAGAAGCGCTGAAGCGAATTCAGCAACAGCAAGCTGCTCGCGAGAAGACAAGGTTTGTGCATAAGTTTCAAGGAAAAGACTGAGAGAAGTCTCAACAGCACCTCCTCCAGCCACAAGTTTCTTGCTTTCCAGAACTCTACGAACAACACAGAGTGAGTCGTGAACCGATCTCTCCATTTCATCGAGCATCACATCGTTCGCTCCACGGAGGATAATGCTGCTGGCAGTACGAGATTTCGGTCCCTTGATGAGAATGAGCTCGTCGTCACTAATTCTTTCTTGAACAATTTCATCGGCATGTCCAAGAAGCGAGGCATCGAAAGCTTCATCTCCTTCCAAAGTAGCCAAGGAAACAGTCAATGTGGCTCCAGTAGCTTTGGCAATTCTCTTCAAGTCTGATTTCTTGCATCGACGAACAGCCATAGCTCCAGATTCGACAAATTGCTTCAAGCACAAATCATCGATACCTCCAGTTGTAAGAACAACGCTGGCTCAGGCTTTCAAAATTTTATCAATGCGGCGTTTGGTAATATCGAATTCTctgaaaattccatagcttaaaaagaaacgaatagtttcaactcacTCTCTGCGAATAGCCTCAAGCTTGGCTGGATCTTCAACAACGACTGAAATACCGAGGTGCATCTTAGCCTTCATCAAAGAGAAATCGAGACATGCGATCTTGGCATTTTGAACACGAAGTGGCATGGCCTGACTGGCAACTGTGCAATTGAGTGCATATCCTTTCACCAAAACTGATTCGCGAGCGCTCTTTCCGTGGGCCTTCAGAACATTGACTGCATTGATAGGATAAGTGACTTTCCCGTTATTTTCCACACGAACAGCTTCCGCGGCATCAACAACCAGCTCTCCGAAGAAATCGGCGTCTctgaaaaatcaattttcttgaagcatagacaacaccaaactcacGGTCCGATAATCTTACTGCTCATGGAAGTTTTGGCAGCGTTGACAACTGATTGTCTACCAATCGAGTCGGAAGTGAATGAGATGTTTTCACTAATGTACTTGACGGCTTCCTTGCACGCGAGACGGTAACCATTGATAATAGTCGTCGGATGAACTTTTTGTTTCACAAGCTCATCGGCTCTCTTCAAGAGCTCAGCCGCCACAATAACGACAGAAGTAGTTCCATCTCCGACCTCCTCGTCTTGCAGCTGTGCAAGTTCTACAAGCACTTTTCCAGCCGGATGCTCAACCTCGAGTTGTTTCAGAATTGTGGCTCCGTCATTTGTGACAATGACATCTCCAACATCATCGACAAGCATTTTATCAAGTCCGACAGGGCCAAGAGATGACTTCACAATATTGGCGATCGCAACTGCCGCGGTGActgcaattaattaatgtatacttatattgagctttcggtgttacCATTCTGAGATCTGATGCCTTGTCCAGTAGTTCTTTTACCGGTGAGGGCAAGAATGGAATCTCCAGCTGATGCCATtac"
    cp.get_possible_restriction_mutations(mutation_zone)

mutate_rest_site_test3 = False
# this test is designed to check the two function, the recursive get_possible_restriction_sites and its improvement
# get_possible_restriction_mutations can both find a restriction site after mutating
if mutate_rest_site_test3:
    cp = initiate_cp()
    rest_enzyme = RestrictionEnzyme(name='Liran', site='GCCGGW', derivatives=('GCCGGA', 'GCCGGT'),
                                    full_site='G/CCGGW')
    cp.restriction_enzymes = [rest_enzyme]
    mutation_zone = SequenceSites(1162, 1167)
    cp.mutated_sites = [PointMutation(index=1163, new_nucleotide="C"), PointMutation(index=1170, new_nucleotide="A")]
    ssodn_mutation_codon_start = 1162
    cp.mutated_strand = "gtggcaaagcttcttcattgtttgaataatgaaaaacgaatacaaacaactttgaaatcaaaacattaaaacttacaacatttcgttcaataaagtatcatcaaaagaagaaaacaaaagctgaacatgagaatttgggataaggagcagcagatcggaattatgtgagaagcacgcggaaaacagggatatataaacggggtaaacgggaaaatTTAAGCGTGGCAATCATCTCCTCCAAGTGGCTCTTGCTTGTCAAGTTTGATGAGGTCATCAATACGCAATATCGTAATGGCTGCCTCAGTGGCGAACTTCAGAGACTTGACCTTACTAAGAGCTGGCTCCAAAATTCCAGCCTCCTTGTTATCGCGGATCGTGCCTTCTTCGAGATCCAAACCAGCCctaaaaaaagagtgaataaactgactcaaattcagaaaacatgaattagacgctttttctaagcacaaaacgaaattttttgaaataaattattttaattttattacattaagctaacatgtaataacctactctttaaaaaaaacattttcacttacCACTTGAGGTGTTGAAGTTGTGGGATCAATTGAGCTTTGGAGTGGTACGCGCGGAGTTTTGTCACTAAATCAGTAGAATCTCTTGCAGCATTGCTTGCCAAAACCTTCGGAATGATGAGAAGCGCTGAAGCGAATTCAGCAACAGCAAGCTGCTCGCGAGAAGACAAGGTTTGTGCATAAGTTTCAAGGAAAAGACTGAGAGAAGTCTCAACAGCACCTCCTCCAGCCACAAGTTTCTTGCTTTCCAGAACTCTACGAACAACACAGAGTGAGTCGTGAACCGATCTCTCCATTTCATCGAGCATCACATCGTTCGCTCCACGGAGGATAATGCTGCTGGCAGTACGAGATTTCGGTCCCTTGATGAGAATGAGCTCGTCGTCACTAATTCTTTCTTGAACAATTTCATCGGCATGTCCAAGAAGCGAGGCATCGAAAGCTTCATCTCCTTCCAAAGTAGCCAAGGAAACAGTCAATGTGGCTCCAGTAGCTTTGGCAATTCTCTTCAAGTCTGATTTCTTGCATCGACGAACAGCCATAGCTCCAGATTCGACAAATTGCTTCAAGCACAAATCATCGATACCTCCAGTTGTAAGAACAACGCTGGCTCAGGCTTTCAAAATTTTATCAATGCGGCGTTTGGTAATATCGAATTCTctgaaaattccatagcttaaaaagaaacgaatagtttcaactcacTCTCTGCGAATAGCCTCAAGCTTGGCTGGATCTTCAACAACGACTGAAATACCGAGGTGCATCTTAGCCTTCATCAAAGAGAAATCGAGACATGCGATCTTGGCATTTTGAACACGAAGTGGCATGGCCTGACTGGCAACTGTGCAATTGAGTGCATATCCTTTCACCAAAACTGATTCGCGAGCGCTCTTTCCGTGGGCCTTCAGAACATTGACTGCATTGATAGGATAAGTGACTTTCCCGTTATTTTCCACACGAACAGCTTCCGCGGCATCAACAACCAGCTCTCCGAAGAAATCGGCGTCTctgaaaaatcaattttcttgaagcatagacaacaccaaactcacGGTCCGATAATCTTACTGCTCATGGAAGTTTTGGCAGCGTTGACAACTGATTGTCTACCAATCGAGTCGGAAGTGAATGAGATGTTTTCACTAATGTACTTGACGGCTTCCTTGCACGCGAGACGGTAACCATTGATAATAGTCGTCGGATGAACTTTTTGTTTCACAAGCTCATCGGCTCTCTTCAAGAGCTCAGCCGCCACAATAACGACAGAAGTAGTTCCATCTCCGACCTCCTCGTCTTGCAGCTGTGCAAGTTCTACAAGCACTTTTCCAGCCGGATGCTCAACCTCGAGTTGTTTCAGAATTGTGGCTCCGTCATTTGTGACAATGACATCTCCAACATCATCGACAAGCATTTTATCAAGTCCGACAGGGCCAAGAGATGACTTCACAATATTGGCGATCGCAACTGCCGCGGTGActgcaattaattaatgtatacttatattgagctttcggtgttacCATTCTGAGATCTGATGCCTTGTCCAGTAGTTCTTTTACCGGTGAGGGCAAGAATGGAATCTCCAGCTGATGCCATtac"
    # print("###RECURSIVE FUNCTION###")
    # print(*cp.get_possible_restriction_sites(cp.mutated_strand, mutation_zone, cp.mutated_sites,
    #                                         ssodn_mutation_codon_start), sep="\n")
    print("###IMPROVED FUNCTION###")
    print(*cp.get_possible_restriction_mutations(mutation_zone), sep="\n")

dsb_vs_mutation_site_test = False
# this test is designed to check if the mutation direction is rightfully chosen even when the DSB is inside the to be
# mutated codon. shouldn't affect if the codon doesn't touch the DSB.
if dsb_vs_mutation_site_test:
    cp = initiate_cp(complete_fiels=False)
    # to use the instance method choose_ssODN_strand, some changes are to be made:
    cp.pam_sites = SequenceSites(31, 33)  # DSB = 28
    cp.sense_mutation_site = 25
    print(cp.choose_ssODN_strand(1, to_aa=AminoAcid.ARGININE))

    cp.sense_mutation_site = 26
    print(cp.choose_ssODN_strand(1, to_aa=AminoAcid.ARGININE))

    # different amino acid, different site to mutate
    cp.sense_mutation_site = 26
    print(cp.choose_ssODN_strand(1, to_aa=AminoAcid.TRYPTOPHAN))

    cp.sense_mutation_site = 27
    print(cp.choose_ssODN_strand(1, to_aa=AminoAcid.CYSTEINE))

    cp.sense_mutation_site = 27
    print(cp.choose_ssODN_strand(1, to_aa=AminoAcid.GLUTAMIC_ACID))

    cp.sense_mutation_site = 28
    print(cp.choose_ssODN_strand(1, to_aa=AminoAcid.TRYPTOPHAN))

    cp.sense_mutation_site = 29
    print(cp.choose_ssODN_strand(1, to_aa=AminoAcid.TRYPTOPHAN))

mutate_rest_site_test5 = False
# this test is designed to check whether a restriction site originated mutations in codon\reattachment section will be
# found
if mutate_rest_site_test5:
    cp = initiate_cp()
    rest_enzyme = RestrictionEnzyme(name='Liran', site='GCCGGW', derivatives=('GCCGGA', 'GCCGGT'),
                                    full_site='G/CCGGW')
    cp.restriction_enzymes = [rest_enzyme]
    mutation_zone = SequenceSites(1162, 1167)
    cp.mutated_sites = [PointMutation(index=1163, new_nucleotide="C"), PointMutation(index=1170, new_nucleotide="A")]
    cp.mutated_strand = "gtggcaaagcttcttcattgtttgaataatgaaaaacgaatacaaacaactttgaaatcaaaacattaaaacttacaacatttcgttcaataaagtatcatcaaaagaagaaaacaaaagctgaacatgagaatttgggataaggagcagcagatcggaattatgtgagaagcacgcggaaaacagggatatataaacggggtaaacgggaaaatTTAAGCGTGGCAATCATCTCCTCCAAGTGGCTCTTGCTTGTCAAGTTTGATGAGGTCATCAATACGCAATATCGTAATGGCTGCCTCAGTGGCGAACTTCAGAGACTTGACCTTACTAAGAGCTGGCTCCAAAATTCCAGCCTCCTTGTTATCGCGGATCGTGCCTTCTTCGAGATCCAAACCAGCCctaaaaaaagagtgaataaactgactcaaattcagaaaacatgaattagacgctttttctaagcacaaaacgaaattttttgaaataaattattttaattttattacattaagctaacatgtaataacctactctttaaaaaaaacattttcacttacCACTTGAGGTGTTGAAGTTGTGGGATCAATTGAGCTTTGGAGTGGTACGCGCGGAGTTTTGTCACTAAATCAGTAGAATCTCTTGCAGCATTGCTTGCCAAAACCTTCGGAATGATGAGAAGCGCTGAAGCGAATTCAGCAACAGCAAGCTGCTCGCGAGAAGACAAGGTTTGTGCATAAGTTTCAAGGAAAAGACTGAGAGAAGTCTCAACAGCACCTCCTCCAGCCACAAGTTTCTTGCTTTCCAGAACTCTACGAACAACACAGAGTGAGTCGTGAACCGATCTCTCCATTTCATCGAGCATCACATCGTTCGCTCCACGGAGGATAATGCTGCTGGCAGTACGAGATTTCGGTCCCTTGATGAGAATGAGCTCGTCGTCACTAATTCTTTCTTGAACAATTTCATCGGCATGTCCAAGAAGCGAGGCATCGAAAGCTTCATCTCCTTCCAAAGTAGCCAAGGAAACAGTCAATGTGGCTCCAGTAGCTTTGGCAATTCTCTTCAAGTCTGATTTCTTGCATCGACGAACAGCCATAGCTCCAGATTCGACAAATTGCTTCAAGCACAAATCATCGATACCTCCAGTTGTAAGAACAACGCTGGCTCAGGCTTTCAAAATTTTATCAATGCGGCGTTTGGTAATATCGAATTCTctgaaaattccatagcttaaaaagaaacgaatagtttcaactcacTCTCTGCGAATAGCCTCAAGCTTGGCTGGATCTTCAACAACGACTGAAATACCGAGGTGCATCTTAGCCTTCATCAAAGAGAAATCGAGACATGCGATCTTGGCATTTTGAACACGAAGTGGCATGGCCTGACTGGCAACTGTGCAATTGAGTGCATATCCTTTCACCAAAACTGATTCGCGAGCGCTCTTTCCGTGGGCCTTCAGAACATTGACTGCATTGATAGGATAAGTGACTTTCCCGTTATTTTCCACACGAACAGCTTCCGCGGCATCAACAACCAGCTCTCCGAAGAAATCGGCGTCTctgaaaaatcaattttcttgaagcatagacaacaccaaactcacGGTCCGATAATCTTACTGCTCATGGAAGTTTTGGCAGCGTTGACAACTGATTGTCTACCAATCGAGTCGGAAGTGAATGAGATGTTTTCACTAATGTACTTGACGGCTTCCTTGCACGCGAGACGGTAACCATTGATAATAGTCGTCGGATGAACTTTTTGTTTCACAAGCTCATCGGCTCTCTTCAAGAGCTCAGCCGCCACAATAACGACAGAAGTAGTTCCATCTCCGACCTCCTCGTCTTGCAGCTGTGCAAGTTCTACAAGCACTTTTCCAGCCGGATGCTCAACCTCGAGTTGTTTCAGAATTGTGGCTCCGTCATTTGTGACAATGACATCTCCAACATCATCGACAAGCATTTTATCAAGTCCGACAGGGCCAAGAGATGACTTCACAATATTGGCGATCGCAACTGCCGCGGTGActgcaattaattaatgtatacttatattgagctttcggtgttacCATTCTGAGATCTGATGCCTTGTCCAGTAGTTCTTTTACCGGTGAGGGCAAGAATGGAATCTCCAGCTGATGCCATtac"
    print(*cp.add_remove_restriction_sites(RestrictionSiteType.INSERTED), sep="\n")

get_codons_test = False
# This test is designed to check if all codons from given range will be extracted. has to be PAM cause CR_RNA cannot cross the end
if get_codons_test:
    def get_codons(section_sites):
        cp = initiate_cp()
        cp.ssODN_mutation_codon_start = 17
        section_to_mutate = MutateSection(4,
                                          DNASection.PAM_SITE,
                                          section_sites)
        return cp.get_relevant_codons(section_to_mutate, cp.ssODN_mutation_codon_start, cp.mutated_strand)


    section_sites = SequenceSites(17, 19)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 1 else print(False)

    section_sites = SequenceSites(17, 20)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 2 else print(False)

    section_sites = SequenceSites(17, 21)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 2 else print(False)

    section_sites = SequenceSites(17, 22)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 2 else print(False)

    section_sites = SequenceSites(16, 18)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 2 else print(False)

    section_sites = SequenceSites(16, 19)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 2 else print(False)

    section_sites = SequenceSites(16, 20)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 3 else print(False)

    section_sites = SequenceSites(15, 18)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 2 else print(False)

    section_sites = SequenceSites(15, 19)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 2 else print(False)

    section_sites = SequenceSites(15, 20)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 3 else print(False)

    section_sites = SequenceSites(13, 20)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 4 else print(False)

    section_sites = SequenceSites(18, 20)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 2 else print(False)

    section_sites = SequenceSites(19, 23)
    codons_data = get_codons(section_sites)
    print(True) if len(codons_data) == 3 else print(False)

codon_mutation_close_to_start_test = False
# this test aims to check what happens if the codon we wish to mutate is located at the beginning of the sequence
existing_rest_sites = ["AclI", "Sau3AI", "DpnI", "AlwI", "MspJI", "HpaII"]
if codon_mutation_close_to_start_test:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 2
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                       favourite_enzymes_names=['Bsp1286I'])
    rest_enzyme = RestrictionEnzyme(name='Bsp1286I', site='GDGCHC',
                                    derivatives=('GGGCAC', 'GAGCAC', 'GGGCTC', 'GTGCTC', 'GGGCCC', 'GTGCCC', 'GAGCTC',
                                                 'GAGCCC', 'GTGCAC'),
                                    full_site='GDGCH/C')
    cp.restriction_enzymes = [rest_enzyme]
    cp.plan_my_crispr(from_aa=AminoAcid.ALANINE,
                      to_aa=AminoAcid.GLYCINE)

codon_mutation_close_to_end_test = False
# this test aims to check what happens if the codon we wish to mutate is located at the end of the sequence
if codon_mutation_close_to_end_test:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 549
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                       favourite_enzymes_names=[])
    cp.plan_my_crispr(from_aa=AminoAcid.ALANINE,
                      to_aa=AminoAcid.GLYCINE)

check_favourite_rest_sites = False
# list of enzymes' names that occur in the sequence without further mutations:
no_added_mutations_enzymes = ['Cac8I', 'BsaXI', 'AclI', 'HpyCH4IV']  # forgot to check for what crrna...
if check_favourite_rest_sites:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    cp = CrisprPlanner(gene_name=worm_gene_name,
                       aa_mutation_site=amino_acid_mutation_site,
                       sense_strand=nt_seq,
                       favourite_enzymes_names=['BspQI', 'Bsp1286I', 'HincII', 'FspI', 'PacI'])
    cp.plan_my_crispr(from_aa=AminoAcid.ASPARAGINE,
                      to_aa=AminoAcid.SERINE)

check_no_sense_strand_given = False
if check_no_sense_strand_given:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    res = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site). \
        plan_my_crispr(from_aa=AminoAcid.ASPARAGINE,
                       to_aa=AminoAcid.SERINE)
    print(res)

# not sure if I finished this test or not
cannot_mutate_pam_site = False
if cannot_mutate_pam_site:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 2
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                       favourite_enzymes_names=[])
    cp.mutated_sites = []
    cp.plan_my_crispr(from_aa=AminoAcid.ALANINE,
                      to_aa=AminoAcid.GLYCINE)

test_is_in_favourites = False
# checking if the function is_in_favourite works. the test only works when cp is initialized with:
# self.restriction_enzymes = FileReader(r"C:\Users\Liran\PycharmProjects\Research\Code\CRISPRR"\
# parsed_restriction_enzymes.txt").get_parsed_restriction_enzymes_list()
if test_is_in_favourites:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 2
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                       favourite_enzymes_names=['Bsp1286I'])
    favourite_rest_enzyme = RestrictionEnzyme(name='Bsp1286I', site='GDGCHC',
                                              derivatives=('GGGCAC', 'GAGCAC', 'GGGCTC', 'GTGCTC', 'GGGCCC', 'GTGCCC',
                                                           'GAGCTC', 'GAGCCC', 'GTGCAC'),
                                              full_site='GDGCH/C')
    non_favourite_rest_enzyme = RestrictionEnzyme(name='Bsp1286II', site='GDGCHC',
                                                  derivatives=('GGGCAC', 'GAGCAC', 'GGGCTC', 'GTGCTC', 'GGGCCC',
                                                               'GTGCCC', 'GAGCTC', 'GAGCCC', 'GTGCAC'),
                                                  full_site='GDGCH/C')
    good_r_site = RestrictionSite(index=None, enzyme=favourite_rest_enzyme, rest_site_type=None)
    bad_r_site = RestrictionSite(index=None, enzyme=non_favourite_rest_enzyme, rest_site_type=None)
    restriction_sites = [good_r_site, bad_r_site]

    good_r_mutation = RestrictionMutation(restriction_site=good_r_site, number_of_mutations=0, mutated_sites=None)
    bad_r_mutation = RestrictionMutation(restriction_site=bad_r_site, number_of_mutations=0, mutated_sites=None)
    restriction_mutations = [good_r_site, bad_r_site]

    if cp.is_in_favourites(restriction_sites) and not cp.is_in_favourites([bad_r_site]) and cp.is_in_favourites(
            [good_r_site]):
        print(True)

    if cp.is_in_favourites(restriction_mutations) and not cp.is_in_favourites([bad_r_mutation]) and cp.is_in_favourites(
            [good_r_mutation]):
        print(True)

test_favourites_are_not_all = False
if test_favourites_are_not_all:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                       favourite_enzymes_names=['BspMI', 'HpyCH4IV', 'AclI', 'PsiI-v2', 'MluCI'])
    print(cp.plan_my_crispr(from_aa=AminoAcid.ASPARAGINE, to_aa=AminoAcid.SERINE))

lab_enzymes = ['AgeI', 'ApaLI', 'AseI', 'BamHI', 'BglII', 'BspHI', 'ClaI', 'EcorI', 'EcorV', 'HaeII', 'HindIII',
               'HpaII', 'HpHI', 'KpnI', 'MscI', 'NcoI', 'NdeI', 'NheI', 'NotI', 'PpuMI', 'PstI', 'PvuII', 'SacI',
               'SacII', 'SbfI', 'SgrAI', 'SnaBI', 'SpeI', 'XbaI', 'XhoI', 'XmaI', 'MluCI', 'RsaI', 'TaqI-v2', 'DpnI',
               'PacI', 'AscI', 'AvaII', 'DdeI']

test_is_in_favourites_2 = False
if test_is_in_favourites_2:
    restriction_sites = [RestrictionSite(index=SequenceSites(start=30553, end=30556),
                                         enzyme=RestrictionEnzyme(name='LpnPI', site='CCDG',
                                                                  derivatives=('CCTG', 'CCAG', 'CCGG'),
                                                                  full_site='CCDG(10/14)'),
                                         rest_site_type=RestrictionSiteType.INSERTED),
                         RestrictionSite(index=SequenceSites(start=30553, end=30556),
                                         enzyme=RestrictionEnzyme(name='HpaII', site='CCGG', derivatives=('CCGG',),
                                                                  full_site='C/CGG'),
                                         rest_site_type=RestrictionSiteType.INSERTED),
                         RestrictionSite(index=SequenceSites(start=30555, end=30556),
                                         enzyme=RestrictionEnzyme(name='FspEI', site='CC', derivatives=('CC',),
                                                                  full_site='CC(12/16)'),
                                         rest_site_type=RestrictionSiteType.INSERTED),
                         RestrictionSite(index=SequenceSites(start=30552, end=30557),
                                         enzyme=RestrictionEnzyme(name='BspEI', site='TCCGGA', derivatives=('TCCGGA',),
                                                                  full_site='T/CCGGA'),
                                         rest_site_type=RestrictionSiteType.INSERTED),
                         RestrictionSite(index=SequenceSites(start=30558, end=30561),
                                         enzyme=RestrictionEnzyme(name='MspJI', site='CNNR',
                                                                  derivatives=('CGGA', 'CTGG',
                                                                               'CGGG', 'CGAA', 'CATA', 'CAGA', 'CCCA',
                                                                               'CACA', 'CCGA', 'CTTG', 'CTAG', 'CGCG',
                                                                               'CATG', 'CCTG', 'CTCA', 'CGTG', 'CGAG',
                                                                               'CACG', 'CGCA', 'CCGG', 'CTCG', 'CCAG',
                                                                               'CCAA', 'CTTA', 'CTGA', 'CCCG', 'CGTA',
                                                                               'CAGG', 'CAAG', 'CAAA', 'CTAA', 'CCTA'),
                                                                  full_site='CNNR(9/13)'),
                                         rest_site_type=RestrictionSiteType.INSERTED),
                         RestrictionSite(index=SequenceSites(start=30553, end=30555),
                                         enzyme=RestrictionEnzyme(name='Nt.CviPII', site='CCD',
                                                                  derivatives=('CCG', 'CCA', 'CCT'),
                                                                  full_site='(0/-1)CCD'),
                                         rest_site_type=RestrictionSiteType.INSERTED),
                         RestrictionSite(index=SequenceSites(start=30552, end=30557),
                                         enzyme=RestrictionEnzyme(name='BsaWI', site='WCCGGW',
                                                                  derivatives=('ACCGGA', 'TCCGGA', 'TCCGGT', 'ACCGGT'),
                                                                  full_site='W/CCGGW'),
                                         rest_site_type=RestrictionSiteType.INSERTED),
                         RestrictionSite(index=SequenceSites(start=30553, end=30556),
                                         enzyme=RestrictionEnzyme(name='MspI', site='CCGG', derivatives=('CCGG',),
                                                                  full_site='C/CGG'),
                                         rest_site_type=RestrictionSiteType.INSERTED)]
    print(CrisprPlanner(gene_name="him-4",
                        aa_mutation_site=1024, favourite_enzymes_names=lab_enzymes).is_in_favourites(restriction_sites))

test_anat_1 = False
if test_anat_1:
    worm_gene_name = 'him-4'
    amino_acid_mutation_site = 1024
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site,
                       favourite_enzymes_names=lab_enzymes)
    print(cp.plan_my_crispr(from_aa=AminoAcid.VALINE, to_aa=AminoAcid.METHIONINE))

test_anat_2 = False
if test_anat_2:
    worm_gene_name = 'him-4'
    amino_acid_mutation_site = 80
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site,
                       favourite_enzymes_names=lab_enzymes)
    print(cp.plan_my_crispr(from_aa=AminoAcid.PROLINE, to_aa=AminoAcid.ARGININE))

test_anat_3 = False
if test_anat_3:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 456
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site,
                       favourite_enzymes_names=lab_enzymes)
    print(cp.plan_my_crispr(from_aa=AminoAcid.ALANINE, to_aa=AminoAcid.GLUTAMIC_ACID))

# A test to check what happens if the codon we wish you mutate have to be changed before the DSB (1) and after (1):
# ACT->ATG. crRNA start at 33
test_dsb_vs_codon_1 = False
if test_dsb_vs_codon_1:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 16  # ACT, dsb before T
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccacat"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq)
    print(cp.plan_my_crispr(from_aa=AminoAcid.THREONINE, to_aa=AminoAcid.METHIONINE))

# A test to check what happens if the codon we wish you mutate have to be changed before the (2) DSB and after (1):
# ACT -> CAA, CAG. crRNA start at 33
test_dsb_vs_codon_2 = False
if test_dsb_vs_codon_2:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 16  # ACT, dsb before T
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccacat"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                       favourite_enzymes_names=lab_enzymes + ["TspRI"])
    print(cp.plan_my_crispr(from_aa=AminoAcid.THREONINE, to_aa=AminoAcid.GLUTAMINE))

# A test to check what happens if the codon we wish you mutate have to be changed before the (0) DSB and after (1):
# Also, it checks if taking NGG from anti-sense strand works the same way. AAG -> AAC (CTT > GTT). crRNA starts at 2116
test_dsb_vs_codon_3 = False
if test_dsb_vs_codon_3:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 9  # AAG (anti-sense), dsb before G
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccacat"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                       favourite_enzymes_names=lab_enzymes)
    print(cp.plan_my_crispr(from_aa=AminoAcid.LEUCINE, to_aa=AminoAcid.VALINE))

# A test to check what happens if the algorithm can't find a favourite site to insert\remove
test_not_found_fav_site_1 = False
if test_not_found_fav_site_1:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 16  # ACT, dsb before T if crRNA starts at 33
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccacat"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                       # favourite_enzymes_names=['PI-PspI'])
                       favourite_enzymes_names=lab_enzymes)
    print(cp.plan_my_crispr(from_aa=AminoAcid.THREONINE, to_aa=AminoAcid.GLUTAMINE))


# Former test didn't have results where mutation is downstream (faster)
test_not_found_fav_site_2 = False
if test_not_found_fav_site_2:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 27  # AAC
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccacat"
    cp = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site, sense_strand=nt_seq,
                       favourite_enzymes_names=['PI-PspI'])
    print(cp.plan_my_crispr(from_aa=AminoAcid.THREONINE, to_aa=AminoAcid.GLUTAMINE))

short_enzymes_list = ['HindIII', 'BglII', 'ClaI', 'BamHI', 'ApaLI', 'HaeII', 'BspHI']
fake_enzyme = ['LiranTest']
# restriction enzyme to passivly mutate:
# LiranTest	TCAGCTGGAGATTCCATTC	TCAGCTGGAGATTCCATTC	TCAGCTGGAGA/TTCCATTC
fake_enzyme2 = ['LiranTest2']
# restriction enzyme to actively mutate
# LiranTest2  TCAGCTGGA  TCAGCTGGA  TCAGC/TGGA

test_random = False
if test_random:
    worm_gene_name = 'cct-1'
    amino_acid_mutation_site = 287
    res = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site,
                        favourite_enzymes_names=short_enzymes_list). \
        plan_my_crispr(from_aa=AminoAcid.ASPARAGINE,
                       to_aa=AminoAcid.ALANINE)
    print(res)

# test to see if function aimed to find already removed restriction sites works.
# need to alter the parsed_restriction_enzymes file and add the relevant restriction enzyme
test_remove_restriction_site_passively = False
if test_remove_restriction_site_passively:
    print("### TEST: REMOVE RESTRICTION SITE ###")
    worm_gene_name = "cct-1"
    amino_acid_mutation_site = 2
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    res = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site,
                        favourite_enzymes_names=fake_enzyme).\
        plan_my_crispr(from_aa=AminoAcid.ALANINE,
                       to_aa=AminoAcid.METHIONINE,
                       crrna='GATTCCATTCTTGCCCTCAC')
    print(res)

test_remove_restriction_site_actively = True
if test_remove_restriction_site_actively:
    print("### TEST: REMOVE RESTRICTION SITE ###")
    worm_gene_name = "cct-1"
    amino_acid_mutation_site = 2
    nt_seq = "gtaATGGCATCAGCTGGAGATTCCATTCTTGCCCTCACCGGTAAAAGAACTACTGGACAAGGCATCAGATCTCAGAATGgtaacaccgaaagctcaatataagtatacattaattaattgcagTCACCGCGGCAGTTGCGATCGCCAATATTGTGAAGTCATCTCTTGGCCCTGTCGGACTTGATAAAATGCTTGTCGATGATGTTGGAGATGTCATTGTCACAAATGACGGAGCCACAATTCTGAAACAACTCGAGGTTGAGCATCCGGCTGGAAAAGTGCTTGTAGAACTTGCACAGCTGCAAGACGAGGAGGTCGGAGATGGAACTACTTCTGTCGTTATTGTGGCGGCTGAGCTCTTGAAGAGAGCCGATGAGCTTGTGAAACAAAAAGTTCATCCGACGACTATTATCAATGGTTACCGTCTCGCGTGCAAGGAAGCCGTCAAGTACATTAGTGAAAACATCTCATTCACTTCCGACTCGATTGGTAGACAATCAGTTGTCAACGCTGCCAAAACTTCCATGAGCAGTAAGATTATCGGACCgtgagtttggtgttgtctatgcttcaagaaaattgatttttcagAGACGCCGATTTCTTCGGAGAGCTGGTTGTTGATGCCGCGGAAGCTGTTCGTGTGGAAAATAACGGGAAAGTCACTTATCCTATCAATGCAGTCAATGTTCTGAAGGCCCACGGAAAGAGCGCTCGCGAATCAGTTTTGGTGAAAGGATATGCACTCAATTGCACAGTTGCCAGTCAGGCCATGCCACTTCGTGTTCAAAATGCCAAGATCGCATGTCTCGATTTCTCTTTGATGAAGGCTAAGATGCACCTCGGTATTTCAGTCGTTGTTGAAGATCCAGCCAAGCTTGAGGCTATTCGCAGAGAgtgagttgaaactattcgtttctttttaagctatggaattttcagAGAATTCGATATTACCAAACGCCGCATTGATAAAATTTTGAAAGCCGGAGCCAACGTTGTTCTTACAACTGGAGGTATCGATGATTTGTGCTTGAAGCAATTTGTCGAATCTGGAGCTATGGCTGTTCGTCGATGCAAGAAATCAGACTTGAAGAGAATTGCCAAAGCTACTGGAGCCACATTGACTGTTTCCTTGGCTACTTTGGAAGGAGATGAAGCTTTCGATGCCTCGCTTCTTGGACATGCCGATGAAATTGTTCAAGAAAGAATTAGTGACGACGAGCTCATTCTCATCAAGGGACCGAAATCTCGTACTGCCAGCAGCATTATCCTCCGTGGAGCGAACGATGTGATGCTCGATGAAATGGAGAGATCGGTTCACGACTCACTCTGTGTTGTTCGTAGAGTTCTGGAAAGCAAGAAACTTGTGGCTGGAGGAGGTGCTGTTGAGACTTCTCTCAGTCTTTTCCTTGAAACTTATGCACAAACCTTGTCTTCTCGCGAGCAGCTTGCTGTTGCTGAATTCGCTTCAGCGCTTCTCATCATTCCGAAGGTTTTGGCAAGCAATGCTGCAAGAGATTCTACTGATTTAGTGACAAAACTCCGCGCGTACCACTCCAAAGCTCAATTGATCCCACAACTTCAACACCTCAAGTGgtaagtgaaaatgttttttttaaagagtaggttattacatgttagcttaatgtaataaaattaaaataatttatttcaaaaaatttcgttttgtgcttagaaaaagcgtctaattcatgttttctgaatttgagtcagtttattcactctttttttagGGCTGGTTTGGATCTCGAAGAAGGCACGATCCGCGATAACAAGGAGGCTGGAATTTTGGAGCCAGCTCTTAGTAAGGTCAAGTCTCTGAAGTTCGCCACTGAGGCAGCCATTACGATATTGCGTATTGATGACCTCATCAAACTTGACAAGCAAGAGCCACTTGGAGGAGATGATTGCCACGCTTAAattttcccgtttaccccgtttatatatccctgttttccgcgtgcttctcacataattccgatctgctgctccttatcccaaattctcatgttcagcttttgttttcttcttttgatgatactttattgaacgaaatgttgtaagttttaatgttttgatttcaaagttgtttgtattcgtttttcattattcaaacaatgaagaagctttgccac"
    res = CrisprPlanner(gene_name=worm_gene_name, aa_mutation_site=amino_acid_mutation_site,
                        favourite_enzymes_names=fake_enzyme2).\
        plan_my_crispr(from_aa=AminoAcid.ALANINE,
                       to_aa=AminoAcid.METHIONINE,
                       crrna='GATTCCATTCTTGCCCTCAC')
    print(res)